Recipe-master/dashboard/urls.py
from django.urls import path
from . import views

urlpatterns = [

    path('', views.MyProfileView.as_view(), name="my_profile_view"),
    path('change-password', views.ChangePasswordView.as_view(), name="change_password_view"),
    path('upload', views.RecipeUploadView.as_view(), name="recipe_upload_view"),
    path('update-recipe/<int:id>', views.RecipeUpdateView.as_view(), name="recipe_update_view"),
    path('my-recipe', views.MyRecipeView.as_view(), name="my_recipe_view"),
    path('my-favourite', views.MyFavouriteView.as_view(), name="my_favourite_view"),
     path('recipe-detail/<pk>', views.RecipeDetailViewDashboard.as_view(), name="recipe_detail_dashboard"),
    path('delete-data/<int:id>', views.DeleteRecipeView, name="delete_recipe"),
    path('set-status/<int:id>', views.SetStatus, name="set_status"),
    path('set-status', views.SetFavourite.as_view(), name="set_favourite"),

]

Recipe-master/home/urls.py
from django.urls import path
from . import views

urlpatterns = [

    path('', views.HomeView.as_view(), name="home_view")

]

Recipe-master/recipe/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('superadmin/', admin.site.urls),
    path('user/', include(('user.urls', 'user'), namespace='user')),
    path('admin/', include(('recipe_admin.urls', 'recipe_admin'), namespace='recipe_admin')),
    path('dashboard/', include(('dashboard.urls', 'dashboard'), namespace='dashboad')),
    path('find-recipe/', include(('find_recipe.urls', 'find_recipe'), namespace='find_recipe')),
    path('', include(('home.urls', 'home'), namespace='home')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Recipe-master/recipe_admin/urls.py
from django.urls import path
from . import views

urlpatterns = [

    path('login/', views.AdminLoginView.as_view(), name="admin_login"),
    path('dashboard', views.AdminDashBoardView.as_view(), name="admin_dashboard"),
    # manage users
    path('manage-users/', views.ManageUsersView.as_view(), name="manage_users"),
    path('add-user/', views.AddUserView.as_view(), name="add_user"),
    path('update-user/<int:id>', views.UpdateUserView.as_view(), name="update_user"),
    path('delete-user/<int:id>', views.DeleteUserView.as_view(), name="delete_user"),
    
    #manage recipes
    path('manage-recipes/', views.ManageRecipeView.as_view(), name="manage_recipe"),
    path('add-recipe/', views.AddRecipeView.as_view(), name="add_recipe"),
    path('update-recipe/<int:id>', views.UpdateRecipeView.as_view(), name="update_recipe"),
    path('delete-recipe/<int:id>', views.DeleteRecipeView.as_view(), name="delete_recipe"),
    
    #manage profile
    path('profile/', views.AdminProfileView.as_view(), name="admin_profile"),
    path('admin-logout/', views.AdminLogoutView, name="admin_logout"),
    
    # manage Tips
    path('manage-tips/', views.ManageRecipeTipsView.as_view(), name="manage_tips"),
    path('add-tip/', views.AddRecipeTipView.as_view(), name="add_tip"),
    path('update-tip/<int:id>', views.UpdateRecipeTipView.as_view(), name="update_tip"),
    path('delete-tip/<int:id>', views.DeleteRecipeTipView.as_view(), name="delete_tip"),

]

Recipe-master/dashboard/models.py
from distutils.command.upload import upload
from django.db import models
from user.models import User
# Create your models here.

class Categories(models.Model):
    name=models.CharField(max_length=50)
    
    def __str__(self) -> str:
        return self.name
    
class Recipe(models.Model):
    name=models.CharField(max_length=50)
    img=models.ImageField(upload_to='recipe_photos',verbose_name="recipe photo")
    video=models.FileField(upload_to="videos" )
    category = models.ForeignKey(Categories,on_delete=models.CASCADE)
    description = models.TextField()
    created_by = models.ForeignKey(User,on_delete=models.CASCADE)
    status = models.BooleanField(default=True)
    rating_points_avg = models.FloatField(default=0,null=True,blank=True)
    no_of_user_rated_points_1 = models.PositiveIntegerField(default=0,null=True,blank=True)
    no_of_user_rated_points_2 = models.PositiveIntegerField(default=0,null=True,blank=True)
    no_of_user_rated_points_3 = models.PositiveIntegerField(default=0,null=True,blank=True)
    no_of_user_rated_points_4 = models.PositiveIntegerField(default=0,null=True,blank=True)
    no_of_user_rated_points_5 = models.PositiveIntegerField(default=0,null=True,blank=True)
    
    def __str__(self) -> str:
        return self.name
    
    
class FavouriteRecipe(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    recipe = models.ForeignKey(Recipe,on_delete=models.CASCADE)
    
    
    def __str__(self) -> str:
        return f'User:-{self.user.username} Recipe:-{self.recipe.name}'

class RecipeTips(models.Model):
    name = models.CharField(max_length=255)
    
    def __str__(self) -> str:
        return self.name

Recipe-master/recipe_admin/models.py
from django.db import models

# Create your models here.

Recipe-master/dashboard/forms.py
from django import forms
from django.contrib.auth.forms import PasswordChangeForm
from django.utils.translation import gettext_lazy as _

class MyPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(widget=forms.TextInput(
        attrs={"class": "form-control password_change", 'type':"Password", 'placeholder': _("Old Password")}), localize=True)
    new_password1 = forms.CharField(widget=forms.TextInput(
        attrs={"class": "form-control password_change", 'type':"Password", 'placeholder': _("New Password")}), localize=True)
    new_password2 = forms.CharField(widget=forms.TextInput(
        attrs={"class": "form-control password_change", 'type':"Password", 'placeholder': _("Confirm Password")}), localize=True)

Recipe-master/dashboard/views.py
from django.http.response import JsonResponse
from django.shortcuts import render
from django.views import generic
from user.models import User
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.urls import reverse
import os
from .forms import MyPasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.db.models import Q
from .models import Categories,Recipe,FavouriteRecipe
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.template.defaulttags import register
# Create your views here.

@method_decorator(login_required(login_url='/user'), name="dispatch")
class MyProfileView(generic.TemplateView):
    template_name = "my-profile.html" 
     
    def get(self,request) :
        user=User.objects.get(id=self.request.user.id)
        return render(request,self.template_name,{"user":user})
    
    def post(self,request):
      
        fullname= request.POST.get("fullname")
      
        email= request.POST.get("email")
        phone= request.POST.get("phone")
       
        if User.objects.filter(mobile_no=phone).filter(~Q(mobile_no=request.user.mobile_no)).exists():
            messages.error(request, 'Mobile Number Already taken')
            return HttpResponseRedirect(reverse('My-Account:myaccount'))
        if User.objects.filter(email=email).filter(~Q(email=request.user.email)).exists():
            messages.error(request, 'Email Already taken') 
            return HttpResponseRedirect(reverse('My-Account:myaccount'))
        User.objects.filter(id=request.user.id).update(
                                        fullname=fullname,
                                                email=email,
                                                  mobile_no=phone)
        
                                       
        if "img" in request.FILES:
            user=request.user
            if user.img:
                image_path=user.img.path
            
                if os.path.exists(user.img.path):
                    os.remove(image_path)
                    user.img=request.FILES["img"]
                    user.save()
            else:
                user.img=request.FILES["img"]
                user.save()
            
        messages.success(request,"Profile updated successfully")
         
        return HttpResponseRedirect(reverse('dashboad:my_profile_view'))
        
            
    
@method_decorator(login_required(login_url='/user'), name="dispatch")   
class ChangePasswordView(generic.TemplateView):
    template_name = "change-password.html" 
    def post(self,request):
        form = MyPasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, "Password updated successfully ")
        else:
            messages.error(request, form.errors)
		   
        return HttpResponseRedirect(reverse('dashboad:change_password_view')) 
    
@method_decorator(login_required(login_url='/user'), name="dispatch")    
class RecipeUploadView(generic.TemplateView):
    template_name = "upload-recipe.html" 

    def get_context_data(self, **kwargs) :
        context=super().get_context_data(**kwargs)
        context['categories'] =Categories.objects.all()
        return context
    
    def post(self,request):
        name= request.POST.get('name')
        photo= request.FILES['photo']
        video= request.FILES['video']
        cat= request.POST.get('category')
        description= request.POST.get('description')
        category=Categories.objects.get(id=cat)
        Recipe.objects.create(name=name,img=photo,video=video,category=category
                              ,description=description,created_by=request.user)
        messages.success(request, "Recipe uploaded successful") 
        return HttpResponseRedirect(reverse('dashboard:my_recipe_view'))
    
@method_decorator(login_required(login_url='/user'), name="dispatch")    
class MyRecipeView(generic.TemplateView):
    template_name = "my-recipes.html" 
    
    def get_context_data(self, **kwargs):
        context=super().get_context_data(**kwargs)
        context['recipes'] = Recipe.objects.filter(created_by = self.request.user)
        return context

@method_decorator(login_required(login_url='/user'), name="dispatch")    
class MyFavouriteView(generic.TemplateView):
    template_name = "my-favourite.html" 
    
    def get_context_data(self, **kwargs):
        context=super().get_context_data(**kwargs)
        context['recipes'] = FavouriteRecipe.objects.filter(user = self.request.user)
        return context
    
    
@method_decorator(login_required(login_url='/user'), name="dispatch")    
class RecipeDetailViewDashboard(generic.DetailView):
    template_name = "recipe-detail.html"
    context_object_name= 'instance' 
    queryset=Recipe.objects.all()
    
    

    
@method_decorator(login_required(login_url='/user'), name="dispatch")    
class RecipeUpdateView(generic.TemplateView):
    template_name = "update-recipe.html" 

    def get_context_data(self, **kwargs) :
        context=super().get_context_data(**kwargs)
        context['categories'] =Categories.objects.all()
        context['instance'] = Recipe.objects.get(id=self.kwargs['id'])
        return context
    
    
    
    def post(self,request,id):
        instance=Recipe.objects.get(id=id)
        name= request.POST.get('name')
        cat= request.POST.get('category')
        description= request.POST.get('description')
        category=Categories.objects.get(id=cat)
        Recipe.objects.filter(id=id).update(name=name,category=category,description=description)
        
        if 'photo' in request.FILES:
            if instance.img:
                image_path=instance.img.path
            
                if os.path.exists(instance.img.path):
                    os.remove(image_path)
                    instance.img=request.FILES["photo"]
                    instance.save()
            
        if 'video' in request.FILES:
            if instance.video:
                image_path=instance.video.path
                if os.path.exists(instance.video.path):
                    os.remove(image_path)
                    instance.video=request.FILES["video"]
                    instance.save()
            
        messages.success(request, "Recipe uploadated successful") 
        return HttpResponseRedirect(reverse('dashboard:my_recipe_view'))
    
def DeleteRecipeView(request,id):
    Recipe.objects.filter(id=id).delete()
    return JsonResponse({'status':True})

def SetStatus(request,id):
    ins=Recipe.objects.get(id=id)
 
    if ins.status:
        Recipe.objects.filter(id=id).update(status=False)
    else:
        Recipe.objects.filter(id=id).update(status=True)
    return JsonResponse({'status':True})

@method_decorator(login_required(login_url='/user'), name="dispatch")    
class SetFavourite(generic.View):
    def post(self,request):
        recipe_id = Recipe.objects.get(id=request.POST.get('value'))
        if FavouriteRecipe.objects.filter(user=request.user).filter(recipe=recipe_id).exists():
            FavouriteRecipe.objects.filter(user=request.user).filter(recipe=recipe_id).delete()
        else :
            FavouriteRecipe.objects.create(user=request.user,recipe=recipe_id)
        return JsonResponse({'status':True})
       
        
        

@register.filter(name='get_favourite_status')
def get_favourite_status(recipe,user):
    
    status=False
    if user.is_authenticated:
        if FavouriteRecipe.objects.filter(user=user).filter(recipe=recipe).exists():
            status=True
    
    return status

   

Recipe-master/templates/recipe_admin/add-recipe.html
{% extends 'recipe_admin/base.html' %}
{% block content %}
<!-- ======= Hero Section ======= -->
<main id="main" class="main">
    <div class="pagetitle">
        <h1 style="color: #ea4989;">Add Recipe</h1>
    </div>
    <!-- End Page Title -->
    {% if messages %}
    {% for message in messages %}
    {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
    <div class="alert alert-danger alert-dismissible" style="text-align: left;">
        <a href="#" class="close" data-bs-dismiss="alert" aria-label="close" style="color: crimson!important">&times;</a>
        <strong>{{message}}</strong>
    </div>
    {% else %}
    <div class="alert alert-success alert-dismissible" style="text-align: left;">
        <a href="#" class="close" data-bs-dismiss="alert" aria-label="close" style="color: crimson!important">&times;</a>
        <strong>{{message}}</strong>
    </div>
    {% endif %}
    {% endfor %}
    {% endif %}
    <section class="section dashboard">
        <div class="card">
            <div class="card-body p-5">
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="row g-4">
                        <div class="col-md-6">
                            <label>Recipe Name</label>
                            <input class="form-control" type="text" required name="name" />
                        </div>
                        <div class="col-md-6">
                            <label>Photo upload</label>
                            <input class="form-control" type="file" name="photo" required />
                        </div>
                        <div class="col-md-6">
                            <label>Tutorial Video</label>
                            <input class="form-control" type="file" name="video" required />
                        </div>
                        <div class="col-md-6">
                            <label>Category</label>
                            <select class="form-select" aria-label="Default select example" name="category">
                                {% for data in categories %}
                                <option value="{{data.id}}" selected>{{data.name}}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="col-md-12">
                            <label>Description</label>
                            <textarea class="form-control h-150" name='description' required /></textarea>
                        </div>
                        <div class="col-md-12">
                            <button type="submit" class="btn btn-danger">Submit</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </section>
</main>
{% endblock %}

Recipe-master/templates/recipe_admin/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <title>Recipe </title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <link href="https://fonts.gstatic.com" rel="preconnect">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">
    <!-- Vendor CSS Files -->
    <link href="{% static 'recipe_admin/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'recipe_admin/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
    <link href="{% static 'recipe_admin/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
    <link href="{% static 'recipe_admin/vendor/simple-datatables/style.css' %}" rel="stylesheet">
    <!-- Template Main CSS File -->
    <link href="{% static 'recipe_admin/css/style.css' %}" rel="stylesheet">
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css">
      <style>
        .swl {
    background-color: #bb3b6d;
    color: white;
    border: 0;
    box-shadow: none;
    font-size: 17px;
    font-weight: 500;
    -webkit-border-radius: 4px;
    border-radius: 5px;
    padding: 10px 32px;
    margin: 26px 5px 0 5px;
    cursor: pointer;
}
      </style>
</head>

<body>
    <!-- ======= Header ======= -->
    <header id="header" class="header fixed-top d-flex align-items-center">
        <div class="d-flex align-items-center justify-content-between">
            <a href="index.html" class="logo d-flex align-items-center">
                <span class="d-none d-lg-block">logo</span>
            </a>
        </div>
        <nav class="header-nav ms-auto">
            <ul class="d-flex align-items-center">
                <li class="nav-item dropdown pe-3">
                    <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown">
                       {% if request.user.is_authenticated %}
                      {% if request.user.img %}
                        <img src="{{request.user.img.url}}" class="rounded-circle">
                      {% else %}
                        <img src="{% static 'dummy-image.png' %}" class="rounded-circle">
                        {% endif %}
                         {% endif %}
                        <span class="d-none d-md-block dropdown-toggle ps-2">Admin</span>
                    </a><!-- End Profile Iamge Icon -->
                    <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li>
                            <a class="dropdown-item d-flex align-items-center" href="{% url  'recipe_admin:admin_profile' %}">
                                <i class="bi bi-person"></i>
                                <span>My Profile</span>
                            </a>
                        </li>
                 
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li>
                            <a class="dropdown-item d-flex align-items-center" href="{% url  'recipe_admin:admin_logout' %}">
                                <i class="bi bi-box-arrow-right"></i>
                                <span>Sign Out</span>
                            </a>
                        </li>
                    </ul><!-- End Profile Dropdown Items -->
                </li><!-- End Profile Nav -->
            </ul>
        </nav><!-- End Icons Navigation -->
    </header><!-- End Header -->
    <!-- ======= Sidebar ======= -->
    <aside id="sidebar" class="sidebar">
        <ul class="sidebar-nav" id="sidebar-nav">
            <li class="nav-item">
                <a class="nav-link " href="{% url 'recipe_admin:admin_dashboard' %}" style="{% if 'dashboard' in request.build_absolute_uri %}background: #ced4de;{% endif %}">
                    <i class="bi bi-grid"></i>
                    <span>Dashboard</span>
                </a>
            </li><!-- End Dashboard Nav -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="{% url  'recipe_admin:manage_users' %}" style="{% if 'manage-users' in request.build_absolute_uri  or 'add-user' in request.build_absolute_uri  or 'update-user' in request.build_absolute_uri %}background: #ced4de;{% endif %}">
                    <i class="bi bi-cloud-upload"></i>
                    <span>Manage Users</span>
                </a>
            </li><!-- End F.A.Q Page Nav -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="{% url  'recipe_admin:manage_recipe' %}" style="{% if 'manage-recipes' in request.build_absolute_uri or 'add-recipe' in request.build_absolute_uri  or 'update-recipe' in request.build_absolute_uri %}background: #ced4de;{% endif %}">
                    <i class="bi bi-cloud-upload"></i>
                    <span>Manage Recipe</span>
                </a>
            </li>
               <li class="nav-item">
                <a class="nav-link collapsed" href="{% url  'recipe_admin:manage_tips' %}" style="{% if 'manage-tips' in request.build_absolute_uri or 'add-tip' in request.build_absolute_uri  or 'update-tip' in request.build_absolute_uri %}background: #ced4de;{% endif %}">
                    <i class="bi bi-cloud-upload"></i>
                    <span>Manage Tips</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link collapsed" href="{% url  'recipe_admin:admin_profile' %}" style="{% if 'profile' in request.build_absolute_uri %}background: #ced4de;{% endif %}">
                    <i class="bi bi-person"></i>
                    <span>My Profile</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link collapsed" href="{% url  'recipe_admin:admin_logout' %}">
                    <i class="bi bi-box-arrow-right"></i>
                    <span>Sign Out</span>
                </a>
            </li>
        </ul>
    </aside><!-- End Sidebar-->
    {% block content %}
    {% endblock %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>
    <!-- Vendor JS Files -->
    <script src="{% static 'recipe_admin/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <!-- Template Main JS File -->
    <script src="{% static 'recipe_admin/js/main.js' %}"></script>
     <script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.js"></script>
    <script type="">
  function readURL(input) {
    if (input.files && input.files[0]) {
        var reader = new FileReader();
        reader.onload = function(e) {
            $('#imagePreview').css('background-image', 'url('+e.target.result +')');
            $('#imagePreview').hide();
            $('#imagePreview').fadeIn(650);
        }
        reader.readAsDataURL(input.files[0]);
    }
}
$("#imageUpload").change(function() {
    readURL(this);
});
</script>


    <Script>
    $(document).ready(function() {
        $(".delete-user").click(function() {
            var delete_value = $(this).data("id");
            console.log(delete_value)
            swal({
                    title: "Are you sure?",
                    text: "You want to delete !",
                    type: "warning",
                    showCancelButton: true,
                  
                    confirmButtonText: 'Yes, delete it!',
                    closeOnConfirm: false,
                },
                function(isConfirm) {
                    if (isConfirm) {
                        var token = '{{csrf_token}}';
                        $.ajax({
                            headers: { "X-CSRFToken": token },
                            url: "/admin/delete-user/"+delete_value,
                            type: "POST",
                            success: function(json) {
                                swal("Done!", "It was succesfully deleted!", "success");
                                location.reload();
                            }
                        });
                    } else {
                        swal("Cancelled", "Your imaginary file is safe :)", "error");
                    }
                })
        });
    });
    </script>
        <Script>
    $(document).ready(function() {
        $(".delete-recipe").click(function() {
            var delete_value = $(this).data("id");
            console.log(delete_value)
            swal({
                    title: "Are you sure?",
                    text: "You want to delete !",
                    type: "warning",
                    showCancelButton: true,
                  
                    confirmButtonText: 'Yes, delete it!',
                    closeOnConfirm: false,
                },
                function(isConfirm) {
                    if (isConfirm) {
                        var token = '{{csrf_token}}';
                        $.ajax({
                            headers: { "X-CSRFToken": token },
                            url: "/admin/delete-recipe/"+delete_value,
                            type: "POST",
                            success: function(json) {
                                swal("Done!", "It was succesfully deleted!", "success");
                                location.reload();
                            }
                        });
                    } else {
                        swal("Cancelled", "Your imaginary file is safe :)", "error");
                    }
                })
        });
    });
    </script>
      <Script>
    $(document).ready(function() {
        $(".delete-tip").click(function() {
            var delete_value = $(this).data("id");
            console.log(delete_value)
            swal({
                    title: "Are you sure?",
                    text: "You want to delete !",
                    type: "warning",
                    showCancelButton: true,
                  
                    confirmButtonText: 'Yes, delete it!',
                    closeOnConfirm: false,
                },
                function(isConfirm) {
                    if (isConfirm) {
                        var token = '{{csrf_token}}';
                        $.ajax({
                            headers: { "X-CSRFToken": token },
                            url: "/admin/delete-tip/"+delete_value,
                            type: "POST",
                            success: function(json) {
                                swal("Done!", "It was succesfully deleted!", "success");
                                location.reload();
                            }
                        });
                    } else {
                        swal("Cancelled", "Your imaginary file is safe :)", "error");
                    }
                })
        });
    });
    </script>
</body>

</html>

Recipe-master/templates/recipe_admin/manage-tips.html
{% extends 'recipe_admin/base.html' %}
{% block content %}
<style>
.star-rating label {
    color: #bbb;
    font-size: 18px;
    padding: 0;
    cursor: pointer;
    transition: all 0.3s ease-in-out;
}
.star-rating input[type=radio] {
    display: none;
}
    </style>
<main id="main" class="main">
    <div class="pagetitle">
        <h1 style="color: #ea4989;">Manage Tips</h1>
    </div>
    <!-- End Page Title -->
    {% if messages %}
    {% for message in messages %}
    {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
    <div class="alert alert-danger alert-dismissible" style="text-align: left;">
        <a href="#" class="close" data-bs-dismiss="alert" aria-label="close" style="color: crimson!important">&times;</a>
        <strong>{{message}}</strong>
    </div>
    {% else %}
    <div class="alert alert-success alert-dismissible" style="text-align: left;">
        <a href="#" class="close" data-bs-dismiss="alert" aria-label="close" style="color: crimson!important">&times;</a>
        <strong>{{message}}</strong>
    </div>
    {% endif %}
    {% endfor %}
    {% endif %}
    <section class="section dashboard">
        <div class="card">
            <div class="card-body p-5">
                <!-- Recent Sales -->
                <a href="{% url 'recipe_admin:add_tip' %}" class="btn btn-primary" role="button" data-toggle="modal" data-target="#exampleModal" style="position: absolute;top: 1%;right: 4%;"><i class="fa fa-plus mr-5"></i>Add Tip</a>
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>Tip Name</th>
                                       <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for data in tips %}
                                    <tr>
                                        <td>{{data.name}}</td>
                              
                                
                                        <td><a href="{% url 'recipe_admin:update_tip' data.id %}" class="d-inline-block btn btn-primary me-2"><i class="bi bi-pencil"></i></a>
                                            <a href="javascript:void(0)" data-id="{{data.id}}" class="d-inline-block btn btn-danger delete-tip"><i class="bi bi-trash"></i></i></a>
                                        </td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                            <!-- <div class="text-end"> <a href="#" class="btn btn-primary">View All</a></div> -->
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</main>
{% endblock %}