Recipe-master/find_recipe/urls.py
from django.urls import path
from . import views

urlpatterns = [

    path('', views.FindRecipeView.as_view(), name="find_recipe_view"),
    path('rating', views.RatingRecipeView.as_view(), name="rating_recipe_view"),
    path('detail/<pk>', views.RecipeDetailView.as_view(), name="recipe_detail"),

]

Recipe-master/home/urls.py
from django.urls import path
from . import views

urlpatterns = [

    path('', views.HomeView.as_view(), name="home_view")

]

Recipe-master/recipe/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('superadmin/', admin.site.urls),
    path('user/', include(('user.urls', 'user'), namespace='user')),
    path('admin/', include(('recipe_admin.urls', 'recipe_admin'), namespace='recipe_admin')),
    path('dashboard/', include(('dashboard.urls', 'dashboard'), namespace='dashboad')),
    path('find-recipe/', include(('find_recipe.urls', 'find_recipe'), namespace='find_recipe')),
    path('', include(('home.urls', 'home'), namespace='home')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Recipe-master/user/urls.py
from django.urls import path
from . import views

urlpatterns = [

    path('', views.LoginView.as_view(), name="login_view"),
    path('register', views.RegisterView.as_view(), name="register_view"),
    path('verify/', views.VerifyAccountView.as_view(), name="verify_account"),
    path('logout/', views.LogoutView, name="logout")

]

Recipe-master/find_recipe/models.py
from django.db import models

# Create your models here.

Recipe-master/home/models.py
from django.db import models

# Create your models here.

Recipe-master/find_recipe/views.py
from django.shortcuts import render
from django.views import generic
from dashboard.models import Recipe,Categories,RecipeTips
from django.http import HttpRequest, JsonResponse
from django.db.models import Q
# Create your views here.



class FindRecipeView(generic.ListView):
    template_name = "find-recipe.html"  
    context_object_name  = 'recipes'
   
    
    def get_context_data(self, **kwargs):
        context=super().get_context_data(**kwargs)
        context['q']=self.request.GET.get('q')
        context['category_list']=Categories.objects.filter(id__in=self.request.GET.getlist('id'))
        context['category'] = Categories.objects.all()
        context['tips'] = RecipeTips.objects.all().order_by('-id')
        return context
    
    def get_queryset(self):
        query=Recipe.objects.filter(status=True)
        
        if self.request.GET.getlist('id'):
            query=query.filter(category__in = Categories.objects.filter(id__in=self.request.GET.getlist('id')))
        if self.request.GET.get('q'):
            q=self.request.GET.get('q')

            query=query.filter(
                 Q(name__icontains=self.request.GET.get('q')) | 
                 Q(description__icontains=self.request.GET.get('q')) |
                 Q(category__name__icontains = self.request.GET.get('q')))
            
            if query:
                pass
            else:
               
                query=Recipe.objects.filter(status=True)
                for data in q.split(' '):
                    query=Recipe.objects.filter(status=True).filter(name__icontains = data)
                   
                    if self.request.GET.getlist('id'):
                        query=query.filter(category__in = Categories.objects.filter(id__in=self.request.GET.getlist('id')))
  
        return query
class RecipeDetailView(generic.DetailView):
    template_name = "detail.html"
    context_object_name= 'instance' 
    queryset=Recipe.objects.all()

class RatingRecipeView(generic.View):   
    def post(self,request):
        value=request.POST.get('value')
        id=request.POST.get('id')     
        ins = Recipe.objects.get(id=id)
        
        print(value,id)
        
        if ins.no_of_user_rated_points_1 or value == '1':
            if value == '1' :
                if ins.no_of_user_rated_points_1:
                    ins.no_of_user_rated_points_1 = ins.no_of_user_rated_points_1+1
                    one= ins.no_of_user_rated_points_1
                else:
                    ins.no_of_user_rated_points_1 = 1 
                    one = 1
            else:
                one =  ins.no_of_user_rated_points_1
        else:
            ins.no_of_user_rated_points_1 = 0
            one=0
        
        if ins.no_of_user_rated_points_2 or value == '2':
            if value == '2' :
                if ins.no_of_user_rated_points_2:
                    ins.no_of_user_rated_points_2 = ins.no_of_user_rated_points_2+1
                    two = ins.no_of_user_rated_points_2
                else:
                    ins.no_of_user_rated_points_2 = 1
                    two = 1
            else:
                two =  ins.no_of_user_rated_points_2
        else:
            ins.no_of_user_rated_points_2 = 0
            two = 0
        
        if ins.no_of_user_rated_points_3 or value == '3':
            if value == '3' :
                if  ins.no_of_user_rated_points_3:
                    ins.no_of_user_rated_points_3 = ins.no_of_user_rated_points_3 + 1
                    three =ins.no_of_user_rated_points_3
                else:
                    ins.no_of_user_rated_points_3 = 1
                    three = 1
            else:
                three = ins.no_of_user_rated_points_3
        else:
            ins.no_of_user_rated_points_3 = 0
            three = 0
        
        if ins.no_of_user_rated_points_4 or value == '4':
            if value == '4' :
                if ins.no_of_user_rated_points_4:
                    ins.no_of_user_rated_points_4 = ins.no_of_user_rated_points_4 + 1
                    four= ins.no_of_user_rated_points_4
                else:
                    ins.no_of_user_rated_points_4 = 1
                    four =1
            else:
                four= ins.no_of_user_rated_points_4
        else:
            ins.no_of_user_rated_points_4 = 0
            four =0
        
        if ins.no_of_user_rated_points_5 or value == '5':
            if value == '5' :
                if ins.no_of_user_rated_points_5:
                    ins.no_of_user_rated_points_5 = ins.no_of_user_rated_points_5 + 1
                    five= ins.no_of_user_rated_points_5
                else:
                    ins.no_of_user_rated_points_5 = 1
                    five = 1
            else:
                five= ins.no_of_user_rated_points_5
        else:
            ins.no_of_user_rated_points_5= 0 
            five = 0
        ins.save()
        
        sum_of_rating= one*1 +  two *2 + three*3 + four*4 + five*5
        total_rating= one + two + three + four + five
        avg=sum_of_rating/total_rating
        ins.rating_points_avg = avg
        ins.save()
        return JsonResponse({'status':1})
    

    
    

     
    

Recipe-master/home/views.py
from django.views import generic
from dashboard.models import Recipe,RecipeTips
# Create your views here.


class HomeView(generic.TemplateView):
    template_name = "home.html"  
    context_object_name  = 'recipes'

    def get_context_data(self, **kwargs):
        context=super().get_context_data(**kwargs)
        context['recipes']=Recipe.objects.filter(status=True)
        context['tips'] = RecipeTips.objects.all().order_by('-id')
        return context

Recipe-master/templates/base-template.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <title>Recipe</title>
    <meta content="" name="description">
    <meta content="" name="keywords">
    <!-- Favicons -->
    <link href="assets/img/favicon.png" rel="icon">
    <link href="{% static 'assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Barlow:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
    <!-- Vendor CSS Files -->
    <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css">
    <!-- Template Main CSS File -->
    <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">
</head>

<body>
    <!-- ======= Header ======= -->
    <header id="header" class="fixed-top d-flex align-items-center">
        <div class="container d-flex align-items-center">
            <div class="logo me-auto">
                <h1><a href="">logo here</a></h1>
            </div>
            <nav id="navbar" class="navbar order-last order-lg-0">
                <ul>
                    <li><a class="nav-link scrollto active" href="{% url 'home:home_view' %}#hero">Home</a></li>
                    <li><a class="nav-link scrollto" href="{% url 'home:home_view' %}#about">About</a></li>
                    <li><a class="nav-link scrollto" href="{% url 'home:home_view' %}#contact">Contact Us</a></li>
                    <li><a class="nav-link scrollto " href="{% url 'find_recipe:find_recipe_view' %}">Find Recipe</a></li>
                        {% if request.user.is_authenticated %}
                       <li><a class="nav-link scrollto " href="{% url 'dashboard:recipe_upload_view' %}">Upload Recipe</a></li>
                          <li><a class="nav-link scrollto " href="{% url 'dashboard:my_favourite_view' %}">Favourite Recipe</a></li>
                          {% endif %}
                    {% if not request.user.is_authenticated %}
                    <li><a class="nav-link scrollto" href="{% url 'user:login_view' %}">Login</a></li>
                    <li><a class="nav-link scrollto" href="{% url 'user:register_view' %}"> Register </a></li>
                    {% endif %}
                    {% if request.user.is_authenticated %}
                    <li class="nav-item dropdown pe-3">
                        <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown">
                            {% if request.user.img %}
                            <img src="{{request.user.img.url}}" alt="Profile" class="rounded-circle">
                            {% else %}
                             <img src="{% static '' %}" alt="Profile" class="rounded-circle">
                            {% endif %}
                            <span class="d-none d-md-block dropdown-toggle ps-2">{% if request.user.is_authenticated %}{{request.user.username}}{% else %}Admin{% endif %}</span>
                        </a><!-- End Profile Iamge Icon -->
                        <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow fs-5">
                            <li>
                                <a class="dropdown-item " href="{% url 'dashboard:my_profile_view' %}">
                                    <i class="bi bi-person me-2 fs-5"></i>
                                    My Profile
                                </a>
                            </li>
                            <li>
                                <a class="dropdown-item d-flex align-items-center" href="{% url 'user:logout' %}">
                                    <i class="bi bi-box-arrow-right me-2 fs-5"></i>
                                    <span>Sign Out</span>
                                </a>
                            </li>
                        </ul><!-- End Profile Dropdown Items -->
                    </li>
                    {% endif %}
                </ul>
                <i class="bi bi-list mobile-nav-toggle"></i>
            </nav><!-- .navbar -->
        </div>
    </header><!-- End Header -->
    {% block content %}
    {% endblock %}
    <!-- ======= Footer ======= -->
    <footer id="footer">
        <div class="container py-4">
            <div class="text-center">
                <div class="copyright">
                    &copy; Copyright <strong><span>Recipe</span></strong>. All Rights Reserved
                </div>
            </div>
        </div>
    </footer><!-- End Footer -->
    <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>
    <!-- Vendor JS Files -->
    <script src="{% static 'assets/vendor/purecounter/purecounter.js' %}"></script>
    <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
    <script src="{% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
    <script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
    <script src="{% static 'assets/vendor/waypoints/noframework.waypoints.js' %}"></script>
    <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.js"></script>
    <!-- Template Main JS File -->
    <script src="assets/js/main.js"></script>
    <Script>
    $(document).ready(function() {
        $(".delete").click(function() {
            var delete_value = $(this).data("id");
            console.log(delete_value)
            swal({
                    title: "Are you sure?",
                    text: "You want to delete !",
                    type: "warning",
                    showCancelButton: true,
                    confirmButtonClass: 'btn-danger',
                    confirmButtonText: 'Yes, delete it!',
                    closeOnConfirm: false,
                },
                function(isConfirm) {
                    if (isConfirm) {
                        var token = '{{csrf_token}}';
                        $.ajax({
                            headers: { "X-CSRFToken": token },
                            url: "/dashboard/delete-data/" + delete_value,
                            type: "POST",
                            success: function(json) {
                                swal("Done!", "It was succesfully deleted!", "success");
                                location.reload();
                            }
                        });
                    } else {
                        swal("Cancelled", "Your imaginary file is safe :)", "error");
                    }
                })
        });
    });
    </script>
    <Script>
    $(document).ready(function() {
        $(".set-status").click(function() {
            var value = $(this).data("id");
            console.log(value)
            swal({
                    title: "Are you sure?",
                    text: "You want to change !",
                    type: "warning",
                    showCancelButton: true,
                    confirmButtonClass: 'btn-danger',
                    confirmButtonText: 'Yes, change it!',
                    closeOnConfirm: false,
                },
                function(isConfirm) {
                    if (isConfirm) {
                        var token = '{{csrf_token}}';
                        $.ajax({
                            headers: { "X-CSRFToken": token },
                            url: "/dashboard/set-status/" + value,
                            type: "POST",
                            success: function(json) {
                                swal("Done!", "It was succesfully deleted!", "success");
                                location.reload();
                            }
                        });
                    } else {
                        swal("Cancelled", "Your imaginary file is safe :)", "error");
                    }
                })
        });
    });
    </script>
    <script>
$(document).on('change', ".short_by", function() {
    var short_by = $(this).val();
    // alert(short_by);
    window.location.href = short_by;
    set_short_filter(short_by);

});

$(document).on("change", ".filters", function() {
    console.log("success")
    set_short_filter();
});


function set_short_filter(set_filter = "") {
    var category_type = "";

    $(".category_type:checked").each(function() {
        category_type = category_type + "&" + $(this).val();
        console.log(category_type);

    });
    var selected = $(".category_type :selected").map((_, e) => e.value).get()

    for (var i = selected.length - 1; i >= 0; i--) {
        if (selected[i] != '') {

            category_type = category_type + "&" + selected[i];
            console.log(category_type)
        }
    }

    var setfilterURL = "";

    if (category_type) { setfilterURL = setfilterURL + category_type };
    if (set_filter) { setfilterURL = setfilterURL + "&" + set_filter; }

    window.location.href = "?" + setfilterURL;

}
</script>
<script>
  $(".rating").on('click', function(e){
    let value = $(this).data('value');
    let id = $(this).data('id');
    console.log(value,id)
    var token = '{{csrf_token}}'
     $.ajax({
          headers: { "X-CSRFToken": token },
        url: "{% url 'find_recipe:rating_recipe_view' %}",
        type: 'POST',
        data: {'value': value,'id':id},
        success: function (d){
         // some processing
         console.log(true)
        }
     })
  
  });
</script>

<script>
  $(".like").on('click', function(e){
    {% if request.user.is_authenticated %}
    let value = $(this).data('recipe_id');

    console.log(value)
    var token = '{{csrf_token}}'
     $.ajax({
          headers: { "X-CSRFToken": token },
        url: "{% url 'dashboard:set_favourite' %}",
        type: 'POST',
        data: {'value': value},
        success: function (d){
         // some processing
         location.reload()
        }
     })
     {% else %}

     alert("Login Or Register to add in favourite")
     {% endif %}
  
  });
</script>

</body>

</html>

Recipe-master/templates/change-password.html
{% extends 'base-template.html' %}
{% block content %}
{% load static %}
<!-- ======= Hero Section ======= -->
<section id="hero" class="d-flex flex-column justify-content-center align-items-center">
    <div class="container text-center text-md-left" data-aos="fade-up">
        <h1>The Recipe Book </h1>
    </div>
</section><!-- End Hero -->
<main id="main">
    <section class="py-5">
        <div class="container">
            <div class="row">
                <div class="col-md-3">
                    {% include "recipe-profile.html" %}
                </div>
                <div class="col-md-9">
                    {% include "tabs-menu.html" %}
                    <form class="mt-4" method="POST">
                        {% csrf_token %}
                        <div class="row mb-3">
                            <label for="currentPassword" class="col-md-4 col-lg-3 col-form-label">Current Password</label>
                            <div class="col-md-8 col-lg-9">
                                <input name="old_password" type="password" class="form-control" id="currentPassword" required>
                            </div>
                        </div>
                        <div class="row mb-3">
                            <label for="newPassword" class="col-md-4 col-lg-3 col-form-label">New Password</label>
                            <div class="col-md-8 col-lg-9">
                                <input name="new_password1" type="password" class="form-control" id="newPassword" required>
                            </div>
                        </div>
                        <div class="row mb-3">
                            <label for="renewPassword" class="col-md-4 col-lg-3 col-form-label">Re-enter New Password</label>
                            <div class="col-md-8 col-lg-9">
                                <input name="new_password2" type="password" class="form-control" id="renewPassword" required>
                            </div>
                        </div>
                        <div class="text-center">
                            <button type="submit" class="btn btn-danger">Change Password</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
</main><!-- End #main -->
{% endblock %}

Recipe-master/templates/find-recipe.html
{% extends 'base-template.html' %}
{% block content %}
{% load static %}
<!-- ======= Hero Section ======= -->
<section id="hero" class="d-flex flex-column justify-content-center align-items-center">
    <div class="container text-center text-md-left" data-aos="fade-up">
        <h1>The Recipe Book </h1>
    </div>
</section><!-- End Hero -->
<main id="main">
     <marquee attribute_name = "attribute_value"....more attributes style="color: #ea4989;">
          <span style="font-weight: 700;">Tips: </span><span>   {% for data in tips %} >>>{{data.name}}{% endfor %}</span>

        <!--     >>>Don’t overcrowd the pan.   >>>Let red meat sit before cutting into it.    >>>Store spices in the right location.   >>>Shut the stove off before eggs are done.  >>>Chop herbs with salt.  >>>Add salt to boiling pasta water.  >>>Always keep a few essentials on hand.  >>>Keep the root of the onion intact to help with slicing.</span> -->
 
</marquee>
    <section class="py-5">
        <div class="container">
            <div class="row">
                <div class="col-md-3">
                    <div class="supliers-left">
                        <div class="filter-menu">
                            <div class="accordion" id="faq">
                                <div class="card">
                                    <div class="card-header bg-danger text-white">
                                        Recipe
                                    </div>
                                    <div class="card-body">
                                        <ul>
                                            {% for data in category %}
                                            {% if data in category_list %}
                                            <li><a href="#" class="filters">{{data.name}}<span><input value="id={{data.id}}" type="checkbox" class="category_type" checked></span></a></li>
                                            {% else %}
                                            <li><a href="#" class="filters">{{data.name}}<span><input value="id={{data.id}}" type="checkbox" class="category_type"></span></a></li>
                                            {% endif %}
                                            {% endfor %}
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-9">
                    <form method="GET" class="mb-3">
                        <div class="input-group mb-3">
                            <input type="search" name="q" value="{{q|default:''}}" class="form-control" aria-label="Amount (to the nearest dollar)">
                            <button type="submit" class="input-group-text bg-danger text-white"><i class="bi bi-search"></i></button>
                        </div>
                    </form>
                    <div class="row g-3">
                        {% for data in recipes %}
                        <div class="col-md-4">
                            <div class="icon-box border rounded-3">
                                <div id="carouselExampleIndicators{{data.id}}" class="carousel slide" data-bs-ride="carousel">
                                    <div class="carousel-inner">
                                        <div class="carousel-item active">
                                            <img src="{{data.img.url}}" width="264px" height="194px" class="img-fluid rounded-3 d-block w-100" alt="">
                                        </div>
                                        <div class="carousel-item">
                                            <!--        <iframe width="100%" height="230" src="{{data.video.url}}" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe> -->
                                            <video width="264px" height="194px" controls>
                                                <source src="{{data.video.url}}" type="video/mp4">
                                                </source>
                                            </video>
                                        </div>
                                    </div>
                                    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators{{data.id}}" data-bs-slide="prev">
                                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                        <span class="visually-hidden">Previous</span>
                                    </button>
                                    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators{{data.id}}" data-bs-slide="next">
                                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                        <span class="visually-hidden">Next</span>
                                    </button>
                                </div>
                                <div class="p-3" style="    height: 251px;">
                                    <h4><a href="{% url 'find_recipe:recipe_detail' data.id %}" target="blank">{{data.name}}</a> </h4>
                                   
                                    <div class="star-rating">
 <div>
  <button style="border: 0px solid #fff;
    background: transparent;margin-left: 67px;" class="like" data-recipe_id="{{data.id}}"> {% if data|get_favourite_status:request.user %}<i class="bi bi-heart-fill"></i>{% else %}<i class="bi bi-heart"></i>{% endif %}</button></div>
                                        <input id="star-5-{{data.name}}" type="radio" class="rating" data-id="{{data.id}}" data-value="5" name="rating" value="star-5-{{data.name}}" />
                                        <label for="star-5-{{data.name}}" title="5 stars">
                                            {% if data.rating_points_avg >= 5 and data.rating_points_avg < 6 %}
                                            <i class="active bi bi-star-fill" style="color: #f2b600;" aria-hidden="true"></i>
                                            {% else %}
                                            <i class="active bi bi-star-fill" aria-hidden="true"></i>
                                            {% endif %}
                                        </label>
                                        <input id="star-4-{{data.id}}" type="radio" class="rating" data-id="{{data.id}}" data-value="4" name="rating" value="star-4-{{data.id}}" />
                                        <label for="star-4-{{data.id}}" title="4 stars">
                                             {% if data.rating_points_avg >= 4 and data.rating_points_avg < 5  or data.rating_points_avg >= 5 and data.rating_points_avg < 6 %}
                                            <i class="active bi bi-star-fill" style="color: #f2b600;" aria-hidden="true"></i>
                                                {% else %}
                                                <i class="active bi bi-star-fill" aria-hidden="true"></i>
                                                {% endif %}
                                        </label>
                                        <input id="star-3-{{data.id}}" type="radio" class="rating" data-id="{{data.id}}" data-value="3" name="rating" value="star-3-{{data.id}}" />
                                        <label for="star-3-{{data.id}}" title="3 stars">
                                                 {% if data.rating_points_avg >= 3 and data.rating_points_avg < 4  or data.rating_points_avg >= 4 and data.rating_points_avg < 5  or data.rating_points_avg >= 5 and data.rating_points_avg < 6 %}
                                             <i class="active bi bi-star-fill" style="color: #f2b600;" aria-hidden="true"></i>
                                                {% else %}
                                                <i class="active bi bi-star-fill" aria-hidden="true"></i>
                                                {% endif %}
                                        </label>
                                        <input id="star-2-{{data.id}}" type="radio" class="rating" data-id="{{data.id}}" data-value="2" name="rating" value="star-2-{{data.id}}" />
                                        <label for="star-2-{{data.id}}" title="2 stars">
                                                  {% if data.rating_points_avg >= 2 and data.rating_points_avg < 3  or  data.rating_points_avg >= 3 and data.rating_points_avg < 4  or data.rating_points_avg >= 4 and data.rating_points_avg < 5  or data.rating_points_avg >= 5 and data.rating_points_avg < 6 %}
                                             <i class="active bi bi-star-fill" style="color: #f2b600;" aria-hidden="true"></i>
                                                {% else %}
                                                <i class="active bi bi-star-fill" aria-hidden="true"></i>
                                                {% endif %}
                                        </label>
                                        <input id="star-1-{{data.id}}" type="radio" class="rating" data-id="{{data.id}}" data-value="1" name="rating" value="star-1-{{data.id}}" />
                                        <label for="star-1-{{data.id}}" title="1 star">
                                            {% if data.rating_points_avg >= 1 and data.rating_points_avg < 2  or  data.rating_points_avg >= 2 and data.rating_points_avg < 3  or  data.rating_points_avg >= 3 and data.rating_points_avg < 4  or data.rating_points_avg >= 4 and data.rating_points_avg < 5 or data.rating_points_avg >= 5 and data.rating_points_avg < 6 %}
                                            <i class="active bi bi-star-fill" style="color: #f2b600;" aria-hidden="true"></i>
                                                {% else %}
                                                <i class="active bi bi-star-fill" aria-hidden="true"></i>
                                                {% endif %}
                                        </label>
                                      
                                    </div>
                                    <p>{{data.description|slice:'0:100'}}....</p>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </section>
</main><!-- End #main -->
{% endblock %}
{% block script %}
{% endblock %}